---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - provisioning.pgmp.me
  resources:
  - dependencygraphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioning.pgmp.me
  resources:
  - dependencygraphs/finalizers
  verbs:
  - update
- apiGroups:
  - provisioning.pgmp.me
  resources:
  - dependencygraphs/status
  verbs:
  - get
  - patch
  - update
